### ISSUE TITLE
undefined method `proto' for nil:NilClass with Modal Dialog (fine with 2.0.4)

### ISSUE THREAD

**Issue by zhimin** [watir/watir-classic#38]
Env: Watir 3.0.0rc2 on Windows XP (update gemspec > RAutomation 0.7)

Here is my script to handle modal dialog, which worked fine with Watir 2.0.4

```
browser.ie.modal_dialog(:title, "Modal title")
puts my_popup.exists?    # => true
puts my_popup.title   # failed
```

Error returned

```
undefined method `proto' for nil:NilClass
watir-3.0.0.rc2/lib/watir/modal_dialog.rb:23:in `locate'
watir-3.0.0.rc2/lib/watir/module.rb:10:in `until_with_timeout'
commonwatir-3.0.0.rc2/lib/watir/wait.rb:18:in `until'
watir-3.0.0.rc2/lib/watir/module.rb:10:in `until_with_timeout'
watir-3.0.0.rc2/lib/watir/modal_dialog.rb:21:in `locate'
watir-3.0.0.rc2/lib/watir/modal_dialog.rb:36:in `document'
watir-3.0.0.rc2/lib/watir/modal_dialog.rb:41:in `title'
```

thanks.
